spring:
  application:
    name: api-gateway-service
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      default-filters:
        - name: RewritePath
          args:
            regexp: /api/v1/(?<segment>.*)
            replacement: /${segment}

      routes:
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                "[redis-rate-limiter.replenishRate]": 2
                "[redis-rate-limiter.burstCapacity]": 2
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/fallback/product

        - id: category-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - name: CircuitBreaker
              args:
                name: categoryServiceCircuitBreaker
                fallbackUri: forward:/fallback/category

        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**

        - id: payment-service-route
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
